version: '3.8'
services:
  axon:
    container_name: axon
    image: axonweb3/axon:amd64-v0.1.0-beta.5
    restart: always
    privileged: true
    ports:
      - 8000:8000
      - 8001:8001
      - 8100:8100
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
    volumes:
      - ./devtools:/app/devtools
      - ./logs:/app/logs
    networks:
      - axon-net
    command: ./axon -c=/app/devtools/chain/config.toml -g=/app/devtools/chain/genesis.json


  faucet-server:
    image: ghcr.io/simon-tl/axon-faucet:latest
    volumes:
      - ./.env.faucet:/.env
    ports:
      - "8502:3000"
    depends_on:
      - faucet-mongo
      - axon
    networks:
      - axon-net

  faucet-mongo:
    image: mongo:latest
    container_name: faucet-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodbpassword
    volumes:
      - "./data/db:/data/db"
      - "./data/log:/data/log"
    ports:
      - "27017:27017"
    networks:
      - axon-net

  db:
    image: postgres:15-alpine
    command: postgres -c 'max_connections=250'
    restart: always
    container_name: 'postgres'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      # POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 27543:5432
    env_file:
      -  ./.env.explorer      
    volumes:
      - "db:/var/lib/postgresql/data"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - axon-net

  blockscan:
    image: ghcr.io/simon-tl/blockscan:${DOCKER_TAG:-latest}
    # depends_on:
    #   - db
    links:
      - db:database
    restart: always
    container_name: 'blockscan'
    # command: 'elixir --name blockscan@127.0.0.1 -S mix do ecto.create, ecto.migrate, phx.server'
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./.env.explorer
    ports:
      - 4020:4020
    depends_on:
      - axon
    networks:
      - axon-net

volumes:
  db:
    driver: local
networks:
  axon-net: